# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea7a5ff1ed404953c6045a33fd63604b1fe0071fcfafd56f80c5b32f11117bed185b4a3b68d092e4f215d2cab50d85b244429865cb0442a0365cc33801b3607b

test:
  secret_key_base: 3f4bf2f265a5a876acd0c00dd1e300d4a94b1059ae78d610a2b4a50a2695f80d95254f5543bcf8f626e88043a6fda555998408ecb96bf623990ff27ec9b449ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
